name: oss

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name:  A job to deploy web(OSS).
    steps:
    - name: Checkout(获取源码)
      uses: actions/checkout@v1
    - name: Setup ossutil(安装阿里云oss工具)
      uses: manyuanrong/setup-ossutil@v1.0
      with:
        endpoint: "oss-cn-shenzhen.aliyuncs.com" # endpoint 可以去oss控制台上查看，主要区分地区
        access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }} # 在阿里云申请子账号，拥有oss的管理权限，获取密钥后，需要配置在github的secrets里面的accesskeys
        access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
    - name: Upload aliyun oss(上传编译后文件到阿里云oss)
      env: 
        BUCKET: sj-help
      run: |
        ossutil cp index.html oss://$BUCKET/ -rf
        ossutil cp _coverpage.md oss://$BUCKET/ -rf
        ossutil cp _navbar.md oss://$BUCKET/ -rf
        ossutil cp _sidebar.md oss://$BUCKET/ -rf
        ossutil cp README.md oss://$BUCKET/ -rf
        ossutil cp sw.js oss://$BUCKET/ -rf
        ossutil cp src oss://$BUCKET/ -rf
